spring:
  application:
    name: Clothify
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clothify
    username: postgres
    password: root
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  profiles:
    include: secret
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          port: 587
          starttls:
            enable: true
    protocol: smtp
server:
  port: 8080

jwt:
  access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS:10080000}
  refresh-token-expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS:10080000}
  secretKey: ${SECRET_KEY:421892e189udsauhnuhwu7iheuiwqghyu8ghhIBEDHUWQBAHDFJSABewqjuihusjahuIHUIDSAHUIDSHAJKSBNAJKDS78AYH2318DUWAHDJSKAdhsja}

app:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USER:default}
    password: ${REDIS_PASS:default}
